### ISSUE TITLE
Cross-File Links

### ISSUE THREAD

**Issue by zachriggle** [sblakey/obsidian-quip#14]
Thank you for such an amazing plugin!

If I have two documents, and each has a `quip: https://quip-xxxx.com/3Z...dR` in its frontmatter, is there any way to get this plugin to create the link?

I've noticed that if I directly use a Quip link verbatim, when uploading from Obsidian to Quip, the rendered Quip document has a real cross-file link.

It seems that this should be somewhat automatable, just to visit each `[[linked]]` file, and pull the `quip:` link from the FEM of the linked-to document.

**Comment by sblakey** [comment]
Working on it. While I haven't found a way to import Quip-style `@Document Name` references and let Quip just find the relevant document, I think I've made the logic path you've described work on my laptop.

Now I'm trying to do the reverse, since I also have an "Import" function in this release: If the imported documents has any links to quip docs, check to see if a local Obsidian note with the same name exists, check to see if it's front matter points to the "same" Quip document, and if so translate the link in the imported document.

Expect to see this in the next release, later this month.
