### ISSUE TITLE
Can't set "platform.quip.com" as the hostname

### ISSUE THREAD

**Issue by mzhu22** [sblakey/obsidian-quip#21]
Seems like that URL is the default, and as of https://github.com/sblakey/obsidian-quip/commit/af1e934ad7286529b4b8a7a786aaec5902cd1b6f, we error if the configured URL is the default value

**Comment by kleinwareio** [comment]
This is intentional as you need to update the URL to match the dev key you provide. Details are listed in this section which tell you what URL to enter based on what URL you use to access quip: 

https://github.com/sblakey/obsidian-quip/tree/master?tab=readme-ov-file#linking-to-your-corporate-quip-instance
